# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_ai_pb2 as game__ai__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameMasterStub(object):
    """The AI System acts as the Game Master
    All AI intelligence lives behind this service — the C++ game server
    calls these RPCs and never runs models directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrompt = channel.unary_unary(
                '/drawfusion.GameMaster/GetPrompt',
                request_serializer=game__ai__pb2.PromptRequest.SerializeToString,
                response_deserializer=game__ai__pb2.PromptResponse.FromString,
                _registered_method=True)
        self.JudgeRound = channel.unary_unary(
                '/drawfusion.GameMaster/JudgeRound',
                request_serializer=game__ai__pb2.JudgeRoundRequest.SerializeToString,
                response_deserializer=game__ai__pb2.JudgeRoundResponse.FromString,
                _registered_method=True)
        self.GetHint = channel.unary_unary(
                '/drawfusion.GameMaster/GetHint',
                request_serializer=game__ai__pb2.HintRequest.SerializeToString,
                response_deserializer=game__ai__pb2.HintResponse.FromString,
                _registered_method=True)
        self.GetFeedback = channel.unary_unary(
                '/drawfusion.GameMaster/GetFeedback',
                request_serializer=game__ai__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=game__ai__pb2.FeedbackResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/drawfusion.GameMaster/HealthCheck',
                request_serializer=game__ai__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=game__ai__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ValidateKeys = channel.unary_unary(
                '/drawfusion.GameMaster/ValidateKeys',
                request_serializer=game__ai__pb2.ValidateKeysRequest.SerializeToString,
                response_deserializer=game__ai__pb2.ValidateKeysResponse.FromString,
                _registered_method=True)


class GameMasterServicer(object):
    """The AI System acts as the Game Master
    All AI intelligence lives behind this service — the C++ game server
    calls these RPCs and never runs models directly.
    """

    def GetPrompt(self, request, context):
        """Generate a creative drawing prompt for a round
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JudgeRound(self, request, context):
        """Score a batch of drawings relative to each other and the prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHint(self, request, context):
        """Get a contextual hint for a struggling player
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeedback(self, request, context):
        """Get detailed feedback on a player's drawing after judging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check — used by C++ server on startup to verify AI service is reachable
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateKeys(self, request, context):
        """Validate custom API keys provided by the lobby host
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrompt,
                    request_deserializer=game__ai__pb2.PromptRequest.FromString,
                    response_serializer=game__ai__pb2.PromptResponse.SerializeToString,
            ),
            'JudgeRound': grpc.unary_unary_rpc_method_handler(
                    servicer.JudgeRound,
                    request_deserializer=game__ai__pb2.JudgeRoundRequest.FromString,
                    response_serializer=game__ai__pb2.JudgeRoundResponse.SerializeToString,
            ),
            'GetHint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHint,
                    request_deserializer=game__ai__pb2.HintRequest.FromString,
                    response_serializer=game__ai__pb2.HintResponse.SerializeToString,
            ),
            'GetFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeedback,
                    request_deserializer=game__ai__pb2.FeedbackRequest.FromString,
                    response_serializer=game__ai__pb2.FeedbackResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=game__ai__pb2.HealthCheckRequest.FromString,
                    response_serializer=game__ai__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ValidateKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateKeys,
                    request_deserializer=game__ai__pb2.ValidateKeysRequest.FromString,
                    response_serializer=game__ai__pb2.ValidateKeysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drawfusion.GameMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drawfusion.GameMaster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameMaster(object):
    """The AI System acts as the Game Master
    All AI intelligence lives behind this service — the C++ game server
    calls these RPCs and never runs models directly.
    """

    @staticmethod
    def GetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drawfusion.GameMaster/GetPrompt',
            game__ai__pb2.PromptRequest.SerializeToString,
            game__ai__pb2.PromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JudgeRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drawfusion.GameMaster/JudgeRound',
            game__ai__pb2.JudgeRoundRequest.SerializeToString,
            game__ai__pb2.JudgeRoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drawfusion.GameMaster/GetHint',
            game__ai__pb2.HintRequest.SerializeToString,
            game__ai__pb2.HintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drawfusion.GameMaster/GetFeedback',
            game__ai__pb2.FeedbackRequest.SerializeToString,
            game__ai__pb2.FeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drawfusion.GameMaster/HealthCheck',
            game__ai__pb2.HealthCheckRequest.SerializeToString,
            game__ai__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drawfusion.GameMaster/ValidateKeys',
            game__ai__pb2.ValidateKeysRequest.SerializeToString,
            game__ai__pb2.ValidateKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
